name: Build and deploy ASP.Net Core app to Azure Web App - amishadeploymentsample

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Staging Slot
        id: deploy-to-staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'amishadeploymentsample'
          slot-name: 'stage'  # Deploy to your correct staging slot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_490F97C5B2FB4E80AD7D923CF0D268A6 }}
          package: .

  swap:
    runs-on: windows-latest
    needs: deploy
    steps:
      - name: Swap Staging to Production
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az webapp deployment slot swap --resource-group amisha.gupta-ResourceGroup --name amishadeploymentsample --slot amishadeploymentsample-stage --target-slot production
