name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "amishaguptaSampleApp"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./CICDWebApplication/CICDWebApplication.csproj

      - name: Build project
        run: dotnet build ./CICDWebApplication/CICDWebApplication.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./CICDWebApplication/CICDWebApplication.csproj --configuration Release --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.Azure_Credentials }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ env.AZURE_WEBAPP_NAME }}"
          package: ./publish
